### ISSUE TITLE
Each model of every episode predicts the same values

### ISSUE THREAD

**Issue by SebGruber1996** [smilesun/rlR#20]
Hey!

Problem is basically in the title.
I tested with CartPole-v0 + AgentDQN and ran 100 learning iterations.
Got the same predictions for all i in 1:100 with perf$list_models[[i]]$pred(...).
Am I missing something here, or is this a bug?

Greetings,
Sebastian

**Comment by smilesun** [comment]
I think this is a bug also in Keras, see keras issue here https://github.com/keras-team/keras/issues/1765
I will fix it soon

**Comment by smilesun** [comment]
fixed, Latest commit d1ab927
