### ISSUE TITLE
Pong-v0 takes forever to run with "AgentDQN" and crashes with "AgentActorCritic"

### ISSUE THREAD

**Issue by SebGruber1996** [smilesun/rlR#22]
env = makeGymEnv("Pong-v0")
agent = makeAgent("...", env)
agent$updatePara(replay.mem = "UniformDB")
perf = agent$learn(1) # I stopped here after waiting for over one hour

**Comment by smilesun** [comment]
I figured out it is storing process which slows things done, which is exactly the aim for the replayDB implementation you implemented? Have you test against the replayDB?  It is easy to find out which one is the time consuming step. How fast is the storage of replayDB for example? @SebGruber1996

**Comment by smilesun** [comment]
This problem does not exist anymore
