### ISSUE TITLE
listAvailAgent() should output either a vector or a data.frame

### ISSUE THREAD

**Issue by ja-thomas** [smilesun/rlR#44]
Currently it seems to be a list only containing the names, which seems pointless.

```
> listAvailAgent(env)
$AgentDQN
[1] "Deep Q learning"

$AgentFDQN
[1] "Frozen Target Deep Q Learning"

$AgentDDQN
[1] "Double Deep QLearning"

$AgentPG
[1] "Policy Gradient Monte Carlo"

$AgentPGBaseline
[1] "Policy Gradient with Baseline"

$AgentActorCritic
[1] "Actor Critic Method"
```

can you add some more useful information? Similar to what is done in mlr with `listLearners`

Also it's not implemented in a very nice way, shouldn't the agents and environments have properties that should be checked against each other? Currently in the code is stuff like `tb[7L]` to filter for a continuous agent, which is quite hacky

**Comment by smilesun** [comment]
i improved that with a dataframe, further information might be added in the future.
