### ISSUE TITLE
Why does makeAgent not apply the default configuration of the agent?

### ISSUE THREAD

**Issue by ja-thomas** [smilesun/rlR#45]
This is really weird.

If I want to create a agent I need to specify the configuration, but to get the default configuration I need the agent?

```
makeAgent("AgentDQN", env = env, conf = getDefaultConf("AgentDQN"))
```

Why isn't the default configuration applied when I would call `makeAgent("AgentDQN", env = env)`.

Also why is the environment required to create the agent?

**Comment by smilesun** [comment]
i Have changed the makeAgent to initAgent which makes more sense, the default configuration is not used due to the consideration that the user should be responsible to configure the conf object, since different scenario requires completely different configuration.
