### ISSUE TITLE
Why is there no Agent class

### ISSUE THREAD

**Issue by ja-thomas** [smilesun/rlR#46]
Wouldn't it be better to have a Agent class that is not associated with an environment yet?

This would make all the stuff with the configuration much easier.

And you probably want to rename the current Agent class to something that shows that this is a "trial" experiment or something so an Agent combined with an environment?

you could have stuff like that

```
agent = makeAgent("AgentDQN")

env1 = makeGymEnv("CarPole-v1")
env2 = makeGymEnv("CarPole-v2")

exp1 = makeExperiment(agent, env1)
exp2 = makeExperiment(agent, env2)

exp1$learn(200)
...
```

I could imagine a similar api than mlr where Agents represent learner and environments represent tasks.

**Comment by smilesun** [comment]
currently there is a function called `repExperiment` in [repeat experiment](https://smilesun.github.io/rlR/reference/repExperiment.html) where you can specify how many run you want

**Comment by smilesun** [comment]
I have changed the makeAgent to initAgent which makes more sense, since an agent always need an environment to learn from.  The semantic initAgent can also indicate that a configuraiton object has to be passed since the user is responsible for what they are doing.
